# Generated by Django 4.0.1 on 2022-01-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationuser',
            table='xxt_accounts_application_users',
        ),
    ]
