# Generated by Django 4.0.1 on 2022-01-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_applicationuser_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationGroup',
            new_name='ApplicationUsersGroup',
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='family_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Отчетство'),
        ),
    ]
