# Generated by Django 4.0.1 on 2022-01-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_applicationgroup_applicationusersgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='applicationusersgroup',
            options={'verbose_name': 'Группу пользователей', 'verbose_name_plural': 'Группы пользователей'},
        ),
    ]
