# Generated by Django 3.2.9 on 2022-01-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWidgets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_page', models.CharField(max_length=255, unique=True, verbose_name='Название страницы')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок страницы')),
                ('const_sys_property', models.CharField(max_length=50, verbose_name='sys_property')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Страницы',
                'db_table': 'xxt_widgets_page',
                'ordering': ['name_page'],
            },
        ),
        migrations.CreateModel(
            name='TypeBrowser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название браузера')),
                ('attribute', models.CharField(max_length=255, unique=True, verbose_name='Строка из User-Agent')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Тип браузера',
                'verbose_name_plural': 'Тип браузера',
                'db_table': 'xxt_widgets_type_browsers',
            },
        ),
        migrations.CreateModel(
            name='WidgetsGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('show_name', models.CharField(default='', max_length=200, verbose_name='Отображаемое имя на странице')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('index_number', models.IntegerField(verbose_name='Порядок вывода')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('access_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Группа пользователей')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='widgets.pagewidgets', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Группу карточек',
                'verbose_name_plural': 'Группы карточек',
                'db_table': 'xxt_widgets_groups',
                'ordering': ['index_number'],
            },
        ),
        migrations.CreateModel(
            name='MemoryWidgets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='Включена')),
                ('index_number', models.IntegerField(verbose_name='Порядок вывода')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('content', models.TextField(max_length=255, null=True, verbose_name='Текст памятки')),
                ('type', models.CharField(default='memory_widget', max_length=50)),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')),
                ('browser_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='widgets.typebrowser', verbose_name='Тип браузера')),
                ('widgets_groups', models.ManyToManyField(to='widgets.WidgetsGroups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Памятку',
                'verbose_name_plural': 'Список памяток',
                'db_table': 'xxt_widgets_memory',
                'ordering': ['index_number'],
            },
        ),
        migrations.CreateModel(
            name='LinkWidgets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='Включена')),
                ('index_number', models.IntegerField(verbose_name='Порядок вывода')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('type', models.CharField(default='link_widget', max_length=50)),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')),
                ('browser_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='widgets.typebrowser', verbose_name='Тип браузера')),
                ('widgets_groups', models.ManyToManyField(to='widgets.WidgetsGroups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ссылку',
                'verbose_name_plural': 'Список ссылок',
                'db_table': 'xxt_widgets_link',
                'ordering': ['index_number'],
            },
        ),
    ]
