# Generated by Django 4.0.1 on 2022-02-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_alter_linkwidgets_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkwidgets',
            name='browser_type',
        ),
        migrations.AddField(
            model_name='linkwidgets',
            name='browser_type',
            field=models.ManyToManyField(to='widgets.TypeBrowser', verbose_name='Браузеры'),
        ),
        migrations.RemoveField(
            model_name='memorywidgets',
            name='browser_type',
        ),
        migrations.AddField(
            model_name='memorywidgets',
            name='browser_type',
            field=models.ManyToManyField(to='widgets.TypeBrowser', verbose_name='Браузеры'),
        ),
    ]
