# Generated by Django 4.0.1 on 2022-02-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('widgets', '0003_remove_linkwidgets_browser_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetsgroups',
            name='access_group',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Группы пользователей'),
        ),
    ]
